### ISSUE TITLE
I suggest not deprecate for findAll() method

### ISSUE THREAD

**Issue by SlavaAurim** [modul-is/orm#9]
Hi! This is a great project and a beautiful continuation of life for YetORM! I am currently mastering v2 with PHP 8. 

I would like to ask you not to delete the Repository::findAll method because it seems to me a very logical and elegant abstraction. Specific repositories may eventually hide their logic for default filters in it (for example, ['active'= > true, deleted=> 'false']), but for now if this is not necessary - use the basic finAll(). And to find realy all records - use finBy([]).

**Comment by kravcik** [comment]
Currently we working on new version. Plan was delete findAll in final release, that is reason why this function was deprecated.

But I think this abstraction can stay.

Thanks for suggestion!
